spring.application.name=tp3-arqui
server.port=8080

# ===== Base de datos: MySQL (Docker), la misma configuracion que la Entrega 2 =====
spring.datasource.url=jdbc:mysql://localhost:3306/integrador?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# create: borra y recrea las tablas en cada arranque (los CSV se vuelven a cargar)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Que no muestre el stacktrace en las respuestas de error
server.error.include-stacktrace=never